import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'
import router from './router'
import './assets/base.css'

import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Import icons
import {
  faPlus,
  faEye,
  faEdit,
  faTrash,
  faCog,
  faArrowLeft,
  faDatabase,
  faBahtSign,
  faUsers,
  faCreditCard,
  faUser,
  faEnvelope,
  faPhone,
  faGlobe,
  faBuilding,
  faCalendar,
  faClock,
  faLock,
  faSignOutAlt,
  faCamera,
  faBars,
  faCheckCircle,
  faExclamationCircle,
  faMinus,
  faChevronRight,
  faMapMarkerAlt,
  faExclamationTriangle,
  faInfo,
  faTimes,
  faCheck,
  faSpinner,
  faArrowTrendUp,
  faArrowTrendDown,
  faHome,
  faSearch,
  faDownload,
  faUpload,
  faHeart,
  faStar,
  faBookmark,
  faTag,
  faFlag,
  faTrashAlt,
  faCogs,
  faGear,
  faTrophy,
  faGift,
  faLink,
  faWifi,
  faMobile,
  faDesktop,
  faTablet,
  faKeyboard,
  faMouse,
  faHeadphones,
  faMicrophone,
  faVolumeHigh,
  faPrint,
  faSave,
  faFolder,
  faFile,
  faImage,
  faVideo,
  faMusic,
  faGamepad,
  faShoppingCart,
  faWallet,
  faMoneyBill,
  faPiggyBank,
  faChartLine,
  faChartBar,
  faChartPie,
  faChartSimple,
  faIdCard,
  faShield,
  faBug,
  faKey,
  faFingerprint,
  faEyeSlash,
  faUserSecret,
} from '@fortawesome/free-solid-svg-icons'

// Add icons to library
library.add(
  faPlus,
  faEye,
  faEdit,
  faTrash,
  faCog,
  faArrowLeft,
  faDatabase,
  faBahtSign,
  faUsers,
  faCreditCard,
  faUser,
  faEnvelope,
  faPhone,
  faGlobe,
  faBuilding,
  faCalendar,
  faClock,
  faLock,
  faSignOutAlt,
  faCamera,
  faBars,
  faCheckCircle,
  faExclamationCircle,
  faMinus,
  faChevronRight,
  faMapMarkerAlt,
  faExclamationTriangle,
  faInfo,
  faTimes,
  faCheck,
  faSpinner,
  faArrowTrendUp,
  faArrowTrendDown,
  faHome,
  faSearch,
  faDownload,
  faUpload,
  faHeart,
  faStar,
  faBookmark,
  faTag,
  faFlag,
  faTrashAlt,
  faCogs,
  faGear,
  faTrophy,
  faGift,
  faLink,
  faWifi,
  faMobile,
  faDesktop,
  faTablet,
  faKeyboard,
  faMouse,
  faHeadphones,
  faMicrophone,
  faVolumeHigh,
  faPrint,
  faSave,
  faFolder,
  faFile,
  faImage,
  faVideo,
  faMusic,
  faGamepad,
  faShoppingCart,
  faWallet,
  faMoneyBill,
  faPiggyBank,
  faChartLine,
  faChartBar,
  faChartPie,
  faChartSimple,
  faIdCard,
  faShield,
  faBug,
  faKey,
  faFingerprint,
  faEyeSlash,
  faUserSecret,
)

const app = createApp(App)
const pinia = createPinia()

app.component('FontAwesomeIcon', FontAwesomeIcon)
app.use(pinia)
app.use(router)

app.mount('#app')
